name: Deploy Hugo ğŸ§£ # ä»»å›å–œæ¬¢

on:
  push:
    branches:
      - master   # master æ›´æ–°è§¦å‘

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: å®‰è£… Hugo...
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: ç¼–è¯‘... 
        run: hugo

      - name: éƒ¨ç½²...
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }} # personal_token è¿™é‡Œæ–°å»ºä¸€ä¸ª https://github.com/settings/tokens
          PUBLISH_BRANCH: gh-pages  # æ¨é€åˆ°å½“å‰ gh-pages åˆ†æ”¯
          PUBLISH_DIR: ./public  # hugo ç”Ÿæˆåˆ° public ä½œä¸ºè·Ÿç›®å½•
          commit_message: ${{ github.event.head_commit.message }}
